// web/rustploy/src/routes/settings/users/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Users, Plus, Trash2, Shield, Mail, Loader2, MoreVertical } from '@lucide/svelte';
	import PageLayout from '$lib/components/PageLayout.svelte';
	import { getAuthSession } from '$lib/auth';
	import * as Card from '$lib/components/ui/card';
	import * as Table from '$lib/components/ui/table';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import * as Dialog from '$lib/components/ui/dialog';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import * as Select from '$lib/components/ui/select';

	const session = getAuthSession();
	if (!session) goto('/auth', { replaceState: true });

	let showInvite = $state(false);

	const users = [
		{ id: 1, email: 'admin@example.com', name: 'Admin User', role: 'owner', status: 'active', createdAt: '2026-01-15' },
		{ id: 2, email: 'dev@example.com', name: 'Dev User', role: 'admin', status: 'active', createdAt: '2026-03-20' },
		{ id: 3, email: 'ops@example.com', name: 'Ops User', role: 'member', status: 'active', createdAt: '2026-05-10' },
		{ id: 4, email: 'invited@example.com', name: '—', role: 'member', status: 'pending', createdAt: '2026-07-01' }
	];

	const invitations = [
		{ id: 1, email: 'newdev@example.com', role: 'member', expiresAt: '2026-07-20' }
	];

	const roleColors: Record<string, string> = {
		owner: 'default',
		admin: 'secondary',
		member: 'outline'
	};
</script>

<PageLayout>
	<header class="flex items-center gap-2 px-6 py-3 border-b border-border text-sm">
		<Users class="w-4 h-4 text-muted-foreground" />
		<span class="font-medium">Users</span>
	</header>

	<main class="flex-1 p-6 overflow-y-auto animate-fade-up">
		<div class="w-full space-y-6">
			<!-- Users Table -->
			<Card.Root>
				<Card.Header>
					<div class="flex items-center justify-between">
						<div>
							<Card.Title class="text-base flex items-center gap-2">
								<Users class="w-4 h-4 text-muted-foreground" />
								Team Members
							</Card.Title>
							<Card.Description>Manage who has access to your organization</Card.Description>
						</div>
						<Button size="sm" class="gap-1.5 text-xs" onclick={() => (showInvite = true)}>
							<Plus class="w-3.5 h-3.5" />
							Invite Member
						</Button>
					</div>
				</Card.Header>
				<Card.Content class="p-0">
					<Table.Root>
						<Table.Header>
							<Table.Row>
								<Table.Head>User</Table.Head>
								<Table.Head>Role</Table.Head>
								<Table.Head>Status</Table.Head>
								<Table.Head>Joined</Table.Head>
								<Table.Head class="w-12"></Table.Head>
							</Table.Row>
						</Table.Header>
						<Table.Body>
							{#each users as user (user.id)}
								<Table.Row>
									<Table.Cell>
										<div>
											<p class="text-sm font-medium">{user.name}</p>
											<p class="text-xs text-muted-foreground">{user.email}</p>
										</div>
									</Table.Cell>
									<Table.Cell>
										<Badge variant={roleColors[user.role] === 'default' ? 'default' : roleColors[user.role] === 'secondary' ? 'secondary' : 'outline'} class="text-[10px] capitalize">{user.role}</Badge>
									</Table.Cell>
									<Table.Cell>
										{#if user.status === 'active'}
											<Badge variant="default" class="text-[10px]">Active</Badge>
										{:else}
											<Badge variant="secondary" class="text-[10px]">Pending</Badge>
										{/if}
									</Table.Cell>
									<Table.Cell class="text-xs text-muted-foreground">{user.createdAt}</Table.Cell>
									<Table.Cell>
										<DropdownMenu.Root>
											<DropdownMenu.Trigger>
												<Button variant="ghost" size="sm" class="h-7 w-7 p-0">
													<MoreVertical class="w-3.5 h-3.5" />
												</Button>
											</DropdownMenu.Trigger>
											<DropdownMenu.Content align="end">
												<DropdownMenu.Item>Change Role</DropdownMenu.Item>
												<DropdownMenu.Item>Permissions</DropdownMenu.Item>
												<DropdownMenu.Separator />
												<DropdownMenu.Item class="text-destructive">Remove</DropdownMenu.Item>
											</DropdownMenu.Content>
										</DropdownMenu.Root>
									</Table.Cell>
								</Table.Row>
							{/each}
						</Table.Body>
					</Table.Root>
				</Card.Content>
			</Card.Root>

			<!-- Pending Invitations -->
			<Card.Root>
				<Card.Header>
					<Card.Title class="text-base flex items-center gap-2">
						<Mail class="w-4 h-4 text-muted-foreground" />
						Pending Invitations
					</Card.Title>
					<Card.Description>Invitations that haven't been accepted yet</Card.Description>
				</Card.Header>
				<Card.Content>
					{#if invitations.length === 0}
						<p class="text-sm text-muted-foreground text-center py-6">No pending invitations</p>
					{:else}
						<div class="flex flex-col gap-2">
							{#each invitations as inv (inv.id)}
								<div class="flex items-center justify-between p-3 rounded-lg border">
									<div class="flex items-center gap-3">
										<Mail class="w-4 h-4 text-muted-foreground" />
										<div>
											<p class="text-sm font-medium">{inv.email}</p>
											<p class="text-[11px] text-muted-foreground">Expires: {inv.expiresAt} · Role: {inv.role}</p>
										</div>
									</div>
									<Button variant="ghost" size="sm" class="h-7 w-7 p-0">
										<Trash2 class="w-3.5 h-3.5 text-destructive" />
									</Button>
								</div>
							{/each}
						</div>
					{/if}
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</PageLayout>

<Dialog.Root bind:open={showInvite}>
	<Dialog.Content class="sm:max-w-md">
		<Dialog.Header>
			<Dialog.Title>Invite Member</Dialog.Title>
			<Dialog.Description>Send an invitation to join your organization</Dialog.Description>
		</Dialog.Header>
		<div class="space-y-4 py-4">
			<div class="space-y-1.5">
				<Label class="text-xs">Email Address</Label>
				<Input type="email" placeholder="user@example.com" />
			</div>
			<div class="space-y-1.5">
				<Label class="text-xs">Role</Label>
				<Select.Root type="single">
					<Select.Trigger class="w-full"><span class="text-sm text-muted-foreground">Select role...</span></Select.Trigger>
					<Select.Content>
						<Select.Item value="admin">Admin</Select.Item>
						<Select.Item value="member">Member</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>
		</div>
		<Dialog.Footer>
			<Button variant="outline" size="sm" onclick={() => (showInvite = false)}>Cancel</Button>
			<Button size="sm" class="gap-1.5"><Mail class="w-3.5 h-3.5" />Send Invite</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>

// web/rustploy/src/pages/settings/users/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Users, Plus, Shield, Mail, Trash2, UserPlus } from 'lucide-react';
import { PageLayout } from '$lib/../components/PageLayout';
import { getAuthSession } from '$lib/auth';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '$lib/../components/ui/card';
import { Button } from '$lib/../components/ui/button';
import { Badge } from '$lib/../components/ui/badge';
import { toastSuccess } from '$lib/toast';

export default function UsersPage() {
	const navigate = useNavigate();
	const session = getAuthSession();

	if (!session) {
		setTimeout(() => navigate('/auth', { replace: true }), 0);
	}

	const [users, setUsers] = useState([
		{ id: 'usr-1', name: 'Aditya Sahu', email: 'admin@rustploy.dev', role: 'Owner', status: 'Active', joinedAt: 'Jun 12, 2026' },
		{ id: 'usr-2', name: 'Aman Kumar', email: 'aman@example.com', role: 'Admin', status: 'Active', joinedAt: 'Jun 15, 2026' },
		{ id: 'usr-3', name: 'Sarah Chen', email: 'sarah@example.com', role: 'Developer', status: 'Pending', joinedAt: 'Jul 01, 2026' }
	]);

	function removeUser(id: string) {
		setUsers((prev) => prev.filter((u) => u.id !== id));
		toastSuccess('User removed from organization');
	}

	return (
		<PageLayout>
			<header className="flex items-center justify-between px-6 py-3 border-b border-[#262626] text-xs bg-[#0A0A0A] shrink-0">
				<div className="flex items-center gap-2">
					<Users className="w-3.5 h-3.5 text-[#a1a1aa]" />
					<span className="font-medium text-[#FAFAFA]">Users & Roles</span>
				</div>
			</header>

			<main className="flex-1 m-3.5 overflow-y-auto p-7 animate-fade-up min-h-0">
				<div className="max-w-5xl mx-auto space-y-6">
					<div className="flex items-center justify-between">
						<div>
							<h1 className="text-3xl font-bold tracking-tight text-[#FAFAFA]">Users & Access Control</h1>
							<p className="text-sm text-[#a1a1aa] mt-1">Manage team members, roles, and invitation status</p>
						</div>
						<Button size="sm" className="gap-1.5 text-xs font-semibold bg-[#FAFAFA] hover:bg-[#e4e4e7] text-[#0A0A0A] cursor-pointer">
							<UserPlus className="w-4 h-4" /> Invite Member
						</Button>
					</div>

					<Card className="bg-[#171717] border border-[#262626] rounded-xl shadow-md overflow-hidden">
						<CardContent className="p-0">
							<table className="w-full text-left text-xs">
								<thead className="bg-[#141414] border-b border-[#262626] text-[#737373] uppercase tracking-wider font-semibold">
									<tr>
										<th className="px-5 py-3">MEMBER</th>
										<th className="px-5 py-3">ROLE</th>
										<th className="px-5 py-3">STATUS</th>
										<th className="px-5 py-3">JOINED</th>
										<th className="px-5 py-3 text-right">ACTION</th>
									</tr>
								</thead>
								<tbody className="divide-y divide-[#262626]">
									{users.map((u) => (
										<tr key={u.id} className="hover:bg-[#262626]/30 transition-colors">
											<td className="px-5 py-3.5 font-semibold text-[#FAFAFA]">
												<div className="flex items-center gap-2.5">
													<div className="w-7 h-7 rounded-full bg-[#262626] border border-white/10 flex items-center justify-center font-bold text-xs text-[#FAFAFA]">
														{u.name[0]}
													</div>
													<div>
														<p>{u.name}</p>
														<p className="text-[10px] font-mono text-[#737373]">{u.email}</p>
													</div>
												</div>
											</td>
											<td className="px-5 py-3.5">
												<Badge variant="outline" className="text-[10px] font-mono border-[#262626] text-[#FAFAFA] bg-[#262626]">
													{u.role}
												</Badge>
											</td>
											<td className="px-5 py-3.5">
												<Badge variant="outline" className={`text-[10px] ${u.status === 'Active' ? 'border-green-500/30 text-green-400 bg-green-500/10' : 'border-amber-500/30 text-amber-400 bg-amber-500/10'}`}>
													{u.status}
												</Badge>
											</td>
											<td className="px-5 py-3.5 font-mono text-[#a1a1aa]">{u.joinedAt}</td>
											<td className="px-5 py-3.5 text-right">
												{u.role !== 'Owner' && (
													<button onClick={() => removeUser(u.id)} className="p-1.5 rounded-lg border border-[#262626] text-[#a1a1aa] hover:text-red-400 hover:bg-red-500/10 transition-colors cursor-pointer">
														<Trash2 className="w-3.5 h-3.5" />
													</button>
												)}
											</td>
										</tr>
									))}
								</tbody>
							</table>
						</CardContent>
					</Card>
				</div>
			</main>
		</PageLayout>
	);
}
