// web/rustploy/src/pages/settings/tags/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Tag, Plus, Trash2 } from 'lucide-react';
import { PageLayout } from '$lib/../components/PageLayout';
import { getAuthSession } from '$lib/auth';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '$lib/../components/ui/card';
import { Button } from '$lib/../components/ui/button';
import { Input } from '$lib/../components/ui/input';
import { Badge } from '$lib/../components/ui/badge';
import { toastSuccess } from '$lib/toast';

export default function TagsPage() {
	const navigate = useNavigate();
	const session = getAuthSession();

	if (!session) {
		setTimeout(() => navigate('/auth', { replace: true }), 0);
	}

	const [tags, setTags] = useState([
		{ id: 'tag-1', name: 'Production', color: 'bg-green-500/10 text-green-400 border-green-500/30' },
		{ id: 'tag-2', name: 'Staging', color: 'bg-amber-500/10 text-amber-400 border-amber-500/30' },
		{ id: 'tag-3', name: 'Frontend', color: 'bg-blue-500/10 text-blue-400 border-blue-500/30' },
		{ id: 'tag-4', name: 'Backend', color: 'bg-purple-500/10 text-purple-400 border-purple-500/30' }
	]);
	const [newTagName, setNewTagName] = useState('');

	function addTag() {
		if (!newTagName.trim()) return;
		setTags([
			...tags,
			{ id: `tag-${Date.now()}`, name: newTagName.trim(), color: 'bg-[#262626] text-[#FAFAFA] border-white/10' }
		]);
		setNewTagName('');
		toastSuccess('Tag created');
	}

	function removeTag(id: string) {
		setTags(tags.filter((t) => t.id !== id));
	}

	return (
		<PageLayout>
			<header className="flex items-center justify-between px-6 py-3 border-b border-[#262626] text-xs bg-[#0A0A0A] shrink-0">
				<div className="flex items-center gap-2">
					<Tag className="w-3.5 h-3.5 text-[#a1a1aa]" />
					<span className="font-medium text-[#FAFAFA]">Tags</span>
				</div>
			</header>

			<main className="flex-1 m-3.5 overflow-y-auto p-7 animate-fade-up min-h-0">
				<div className="max-w-5xl mx-auto space-y-6">
					<Card className="bg-[#171717] border border-[#262626] rounded-xl shadow-md overflow-hidden">
						<CardHeader className="p-6">
							<CardTitle className="text-base font-semibold text-[#FAFAFA] flex items-center gap-2">
								<Tag className="w-4 h-4 text-[#a1a1aa]" />
								Organization Tags
							</CardTitle>
							<CardDescription className="text-xs text-[#a1a1aa] mt-1">Tags categorize projects and services for filtering and access policies</CardDescription>
						</CardHeader>
						<CardContent className="p-6 pt-0 space-y-5">
							<div className="flex items-center gap-3">
								<Input
									value={newTagName}
									onChange={(e) => setNewTagName(e.target.value)}
									placeholder="New tag name (e.g. Microservices)"
									className="bg-[#141414] border-[#262626] text-[#FAFAFA] max-w-sm text-xs"
								/>
								<Button onClick={addTag} size="sm" className="gap-1.5 text-xs bg-[#FAFAFA] hover:bg-[#e4e4e7] text-[#0A0A0A] cursor-pointer">
									<Plus className="w-3.5 h-3.5" /> Add Tag
								</Button>
							</div>

							<div className="flex flex-wrap gap-2 pt-2">
								{tags.map((t) => (
									<div key={t.id} className="flex items-center gap-2 px-3 py-1.5 rounded-lg border bg-[#141414] border-[#262626]">
										<Badge variant="outline" className={`text-xs ${t.color}`}>{t.name}</Badge>
										<button onClick={() => removeTag(t.id)} className="text-[#737373] hover:text-red-400 transition-colors cursor-pointer">
											<Trash2 className="w-3.5 h-3.5" />
										</button>
									</div>
								))}
							</div>
						</CardContent>
					</Card>
				</div>
			</main>
		</PageLayout>
	);
}

// web/rustploy/src/routes/settings/tags/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Tag, Plus, Trash2, Pencil, Loader2 } from '@lucide/svelte';
	import PageLayout from '$lib/components/PageLayout.svelte';
	import { getAuthSession } from '$lib/auth';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import * as Dialog from '$lib/components/ui/dialog';

	const session = getAuthSession();
	if (!session) goto('/auth', { replaceState: true });

	let tags = $state([
		{ id: 1, name: 'production', color: '#22c55e', count: 5 },
		{ id: 2, name: 'staging', color: '#eab308', count: 3 },
		{ id: 3, name: 'development', color: '#3b82f6', count: 8 },
		{ id: 4, name: 'deprecated', color: '#ef4444', count: 2 },
		{ id: 5, name: 'internal', color: '#8b5cf6', count: 4 }
	]);

	let showCreate = $state(false);
	let newTagName = $state('');
	let newTagColor = $state('#6366f1');
	let creating = $state(false);

	function addTag() {
		if (!newTagName.trim()) return;
		creating = true;
		setTimeout(() => {
			tags = [...tags, { id: Date.now(), name: newTagName.trim().toLowerCase(), color: newTagColor, count: 0 }];
			newTagName = '';
			newTagColor = '#6366f1';
			creating = false;
			showCreate = false;
		}, 300);
	}

	function removeTag(id: number) {
		tags = tags.filter((t) => t.id !== id);
	}
</script>

<PageLayout>
	<header class="flex items-center gap-2 px-6 py-3 border-b border-border text-sm">
		<Tag class="w-4 h-4 text-muted-foreground" />
		<span class="font-medium">Tags</span>
	</header>

	<main class="flex-1 p-6 overflow-y-auto animate-fade-up">
		<div class="w-full">
			<Card.Root>
				<Card.Header>
					<div class="flex items-center justify-between">
						<div>
							<Card.Title class="text-lg flex items-center gap-2">
								<Tag class="w-5 h-5 text-muted-foreground" />
								Tags
							</Card.Title>
							<Card.Description>Create and manage tags to organize your projects</Card.Description>
						</div>
						<Button size="sm" class="gap-1.5 text-xs" onclick={() => (showCreate = true)}>
							<Plus class="w-3.5 h-3.5" />
							Create Tag
						</Button>
					</div>
				</Card.Header>
				<Card.Content class="pt-4 border-t">
					{#if tags.length === 0}
						<div class="flex flex-col items-center gap-3 min-h-[25vh] justify-center">
							<Tag class="w-8 h-8 text-muted-foreground/40" />
							<p class="text-sm text-muted-foreground text-center">
								No tags yet. Create your first tag to start organizing projects.
							</p>
							<Button size="sm" variant="outline" class="gap-1.5 text-xs" onclick={() => (showCreate = true)}>
								<Plus class="w-3.5 h-3.5" />
								Create Tag
							</Button>
						</div>
					{:else}
						<div class="flex flex-col gap-2">
							{#each tags as tag, i (tag.id)}
								<div
									class="flex items-center justify-between p-3 rounded-lg border w-full animate-fade-up"
									style="animation-delay: {i * 30}ms"
								>
									<div class="flex items-center gap-3">
										<div class="w-3.5 h-3.5 rounded-full border border-border/50 shrink-0" style="background-color: {tag.color}"></div>
										<span class="text-sm font-medium">{tag.name}</span>
										{#if tag.color}
											<span class="text-[10px] text-muted-foreground font-mono">{tag.color}</span>
										{/if}
										<Badge variant="outline" class="text-[10px]">{tag.count} services</Badge>
									</div>
									<div class="flex items-center gap-1">
										<Button variant="ghost" size="sm" class="h-7 w-7 p-0">
											<Pencil class="w-3.5 h-3.5" />
										</Button>
										<Button variant="ghost" size="sm" class="h-7 w-7 p-0" onclick={() => removeTag(tag.id)}>
											<Trash2 class="w-3.5 h-3.5 text-destructive" />
										</Button>
									</div>
								</div>
							{/each}
						</div>
					{/if}
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</PageLayout>

<!-- Create Tag Dialog -->
<Dialog.Root bind:open={showCreate}>
	<Dialog.Content class="sm:max-w-md">
		<Dialog.Header>
			<Dialog.Title>Create Tag</Dialog.Title>
			<Dialog.Description>Tags help organize and filter your services</Dialog.Description>
		</Dialog.Header>
		<div class="space-y-4 py-4">
			<div class="space-y-1.5">
				<Label for="tag-name" class="text-xs font-medium">Name</Label>
				<Input id="tag-name" bind:value={newTagName} placeholder="e.g. production" />
			</div>
			<div class="space-y-1.5">
				<Label for="tag-color" class="text-xs font-medium">Color</Label>
				<div class="flex items-center gap-3">
					<input
						id="tag-color"
						type="color"
						bind:value={newTagColor}
						class="w-9 h-9 rounded-md border border-border cursor-pointer bg-transparent p-0.5"
					/>
					<Input value={newTagColor} class="flex-1 font-mono text-xs" disabled />
					{#if newTagName}
						<Badge class="text-[10px]" style="background-color: {newTagColor}; color: white;">{newTagName}</Badge>
					{/if}
				</div>
			</div>
		</div>
		<Dialog.Footer>
			<Button variant="outline" size="sm" onclick={() => (showCreate = false)}>Cancel</Button>
			<Button size="sm" onclick={addTag} disabled={creating || !newTagName.trim()} class="gap-1.5">
				{#if creating}
					<Loader2 class="w-3.5 h-3.5 animate-spin" />
				{:else}
					<Plus class="w-3.5 h-3.5" />
				{/if}
				Create
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
