// web/rustploy/src/routes/settings/server/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Cpu, RefreshCw, Play, Square, Trash2, Terminal, FileText } from '@lucide/svelte';
	import PageLayout from '$lib/components/PageLayout.svelte';
	import { getAuthSession } from '$lib/auth';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import { Separator } from '$lib/components/ui/separator';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Switch } from '$lib/components/ui/switch';

	const session = getAuthSession();
	if (!session) goto('/auth', { replaceState: true });

	let traefikDashboard = $state(true);
	let letsEncryptEmail = $state('admin@example.com');
	let httpPort = $state('80');
	let httpsPort = $state('443');
	let autoCleanup = $state(true);
	let cleanupDays = $state('7');
</script>

<PageLayout>
	<header class="flex items-center gap-2 px-6 py-3 border-b border-border text-sm">
		<Cpu class="w-4 h-4 text-muted-foreground" />
		<span class="font-medium">Web Server</span>
	</header>

	<main class="flex-1 p-6 overflow-y-auto animate-fade-up">
		<div class="w-full space-y-6">
			<!-- Traefik Config -->
			<Card.Root>
				<Card.Header>
					<Card.Title class="text-base">Traefik Configuration</Card.Title>
					<Card.Description>Configure your reverse proxy settings</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-4">
					<div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
						<div class="space-y-1.5">
							<Label class="text-xs">HTTP Port</Label>
							<Input bind:value={httpPort} placeholder="80" />
						</div>
						<div class="space-y-1.5">
							<Label class="text-xs">HTTPS Port</Label>
							<Input bind:value={httpsPort} placeholder="443" />
						</div>
					</div>
					<div class="space-y-1.5">
						<Label class="text-xs">Let's Encrypt Email</Label>
						<Input bind:value={letsEncryptEmail} placeholder="admin@example.com" />
					</div>
					<Separator />
					<div class="flex items-center justify-between">
						<div>
							<p class="text-sm font-medium">Traefik Dashboard</p>
							<p class="text-[11px] text-muted-foreground">Enable the Traefik web dashboard</p>
						</div>
						<Switch bind:checked={traefikDashboard} />
					</div>
				</Card.Content>
			</Card.Root>

			<!-- Server Actions -->
			<Card.Root>
				<Card.Header>
					<Card.Title class="text-base">Server Actions</Card.Title>
					<Card.Description>Manage Traefik and server processes</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-3">
					<div class="flex flex-wrap gap-2">
						<Button variant="outline" size="sm" class="gap-1.5 text-xs"><RefreshCw class="w-3.5 h-3.5" />Reload Traefik</Button>
						<Button variant="outline" size="sm" class="gap-1.5 text-xs"><Terminal class="w-3.5 h-3.5" />Terminal</Button>
						<Button variant="outline" size="sm" class="gap-1.5 text-xs"><FileText class="w-3.5 h-3.5" />View Logs</Button>
					</div>
				</Card.Content>
			</Card.Root>

			<!-- Docker Cleanup -->
			<Card.Root>
				<Card.Header>
					<Card.Title class="text-base">Docker Cleanup</Card.Title>
					<Card.Description>Automatically clean up unused Docker resources</Card.Description>
				</Card.Header>
				<Card.Content class="space-y-4">
					<div class="flex items-center justify-between">
						<div>
							<p class="text-sm font-medium">Auto Cleanup</p>
							<p class="text-[11px] text-muted-foreground">Remove unused images, containers, and volumes</p>
						</div>
						<Switch bind:checked={autoCleanup} />
					</div>
					{#if autoCleanup}
						<div class="space-y-1.5">
							<Label class="text-xs">Cleanup interval (days)</Label>
							<Input bind:value={cleanupDays} type="number" class="w-32" />
						</div>
					{/if}
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</PageLayout>

// web/rustploy/src/pages/settings/server/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Settings, Save, RefreshCw, HardDrive } from 'lucide-react';
import { PageLayout } from '$lib/../components/PageLayout';
import { getAuthSession } from '$lib/auth';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '$lib/../components/ui/card';
import { Button } from '$lib/../components/ui/button';
import { Input } from '$lib/../components/ui/input';
import { Label } from '$lib/../components/ui/label';
import { toastSuccess } from '$lib/toast';

export default function ServerSettingsPage() {
	const navigate = useNavigate();
	const session = getAuthSession();

	if (!session) {
		setTimeout(() => navigate('/auth', { replace: true }), 0);
	}

	const [domain, setDomain] = useState('dashboard.rustploy.dev');
	const [sshPort, setSshPort] = useState('22');
	const [saving, setSaving] = useState(false);
	const [pruning, setPruning] = useState(false);

	function save() {
		setSaving(true);
		setTimeout(() => {
			toastSuccess('Server instance settings saved');
			setSaving(false);
		}, 400);
	}

	function pruneDocker() {
		setPruning(true);
		setTimeout(() => {
			toastSuccess('Docker cleanup completed: Freed 4.2 GB disk space');
			setPruning(false);
		}, 800);
	}

	return (
		<PageLayout>
			<header className="flex items-center justify-between px-6 py-3 border-b border-[#262626] text-xs bg-[#0A0A0A] shrink-0">
				<div className="flex items-center gap-2">
					<Settings className="w-3.5 h-3.5 text-[#a1a1aa]" />
					<span className="font-medium text-[#FAFAFA]">Server Settings</span>
				</div>
			</header>

			<main className="flex-1 m-3.5 overflow-y-auto p-7 animate-fade-up min-h-0">
				<div className="max-w-5xl mx-auto space-y-6">
					<Card className="bg-[#171717] border border-[#262626] rounded-xl shadow-md overflow-hidden">
						<CardHeader className="p-6">
							<CardTitle className="text-base font-semibold text-[#FAFAFA] flex items-center gap-2">
								<Settings className="w-4 h-4 text-[#a1a1aa]" />
								Rustploy Core Host System
							</CardTitle>
							<CardDescription className="text-xs text-[#a1a1aa] mt-1">Configure global server domain, ports, and automated system maintenance</CardDescription>
						</CardHeader>
						<CardContent className="p-6 pt-0 space-y-5">
							<div className="space-y-1.5">
								<Label htmlFor="server-domain" className="text-xs text-[#a1a1aa]">Rustploy Dashboard Domain</Label>
								<Input id="server-domain" value={domain} onChange={(e) => setDomain(e.target.value)} className="bg-[#141414] border-[#262626] text-[#FAFAFA]" />
							</div>

							<div className="space-y-1.5">
								<Label htmlFor="ssh-port" className="text-xs text-[#a1a1aa]">Host SSH Port</Label>
								<Input id="ssh-port" value={sshPort} onChange={(e) => setSshPort(e.target.value)} className="bg-[#141414] border-[#262626] text-[#FAFAFA]" />
							</div>

							<div className="pt-2 border-t border-[#262626] flex items-center justify-between">
								<div>
									<p className="text-xs font-semibold text-[#FAFAFA]">Docker Garbage Collection</p>
									<p className="text-[11px] text-[#737373]">Prune unused images, build cache, and stopped containers</p>
								</div>
								<Button variant="outline" size="sm" onClick={pruneDocker} disabled={pruning} className="gap-1.5 text-xs bg-[#262626] border-[#3f3f46] text-[#FAFAFA] hover:bg-[#333333] cursor-pointer">
									<HardDrive className="w-3.5 h-3.5" />
									{pruning ? 'Cleaning…' : 'Prune System'}
								</Button>
							</div>
						</CardContent>
						<CardFooter className="border-t border-[#262626] p-4 flex justify-end bg-[#141414]">
							<Button onClick={save} disabled={saving} size="sm" className="gap-1.5 text-xs font-semibold bg-[#FAFAFA] hover:bg-[#e4e4e7] text-[#0A0A0A] cursor-pointer">
								<Save className="w-3.5 h-3.5" /> {saving ? 'Saving…' : 'Save Host Settings'}
							</Button>
						</CardFooter>
					</Card>
				</div>
			</main>
		</PageLayout>
	);
}
