// web/rustploy/src/pages/settings/destinations/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Layers, Plus, Trash2 } from 'lucide-react';
import { PageLayout } from '$lib/../components/PageLayout';
import { getAuthSession } from '$lib/auth';
import { Card } from '$lib/../components/ui/card';
import { Button } from '$lib/../components/ui/button';
import { toastSuccess } from '$lib/toast';

export default function DestinationsPage() {
	const navigate = useNavigate();
	const session = getAuthSession();

	if (!session) {
		setTimeout(() => navigate('/auth', { replace: true }), 0);
	}

	const [destinations, setDestinations] = useState([
		{ id: 'dest-1', name: 'AWS S3 Production Backups', bucket: 'rustploy-db-backups-prod', region: 'us-east-1', provider: 'Amazon S3' },
		{ id: 'dest-2', name: 'Cloudflare R2 Storage', bucket: 'rustploy-static-assets', region: 'auto', provider: 'Cloudflare R2' }
	]);

	function removeDest(id: string) {
		setDestinations(destinations.filter((d) => d.id !== id));
		toastSuccess('Destination removed');
	}

	return (
		<PageLayout>
			<header className="flex items-center justify-between px-6 py-3 border-b border-[#262626] text-xs bg-[#0A0A0A] shrink-0">
				<div className="flex items-center gap-2">
					<Layers className="w-3.5 h-3.5 text-[#a1a1aa]" />
					<span className="font-medium text-[#FAFAFA]">S3 Destinations</span>
				</div>
			</header>

			<main className="flex-1 m-3.5 overflow-y-auto p-7 animate-fade-up min-h-0">
				<div className="max-w-5xl mx-auto space-y-6">
					<div className="flex items-center justify-between">
						<div>
							<h1 className="text-3xl font-bold tracking-tight text-[#FAFAFA]">S3 Backup Destinations</h1>
							<p className="text-sm text-[#a1a1aa] mt-1">Configure automated database export and backup storage locations</p>
						</div>
						<Button size="sm" className="gap-1.5 text-xs font-semibold bg-[#FAFAFA] hover:bg-[#e4e4e7] text-[#0A0A0A] cursor-pointer">
							<Plus className="w-4 h-4" /> Add S3 Bucket
						</Button>
					</div>

					<div className="grid grid-cols-1 gap-4">
						{destinations.map((d) => (
							<Card key={d.id} className="bg-[#171717] border border-[#262626] rounded-xl p-5 flex items-center justify-between">
								<div className="flex items-center gap-4">
									<div className="w-10 h-10 rounded-lg bg-[#262626] border border-white/10 flex items-center justify-center font-bold text-sm text-[#FAFAFA]">
										<Layers className="w-5 h-5" />
									</div>
									<div>
										<h2 className="text-base font-semibold text-[#FAFAFA]">{d.name}</h2>
										<p className="text-xs text-[#a1a1aa] font-mono mt-0.5">{d.provider} · Bucket: s3://{d.bucket} ({d.region})</p>
									</div>
								</div>
								<button onClick={() => removeDest(d.id)} className="p-2 rounded-lg border border-[#262626] bg-[#262626] text-[#a1a1aa] hover:text-red-400 hover:bg-red-500/10 transition-colors cursor-pointer">
									<Trash2 className="w-4 h-4" />
								</button>
							</Card>
						))}
					</div>
				</div>
			</main>
		</PageLayout>
	);
}

// web/rustploy/src/routes/settings/destinations/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Layers, Plus, Trash2, CheckCircle } from '@lucide/svelte';
	import PageLayout from '$lib/components/PageLayout.svelte';
	import { getAuthSession } from '$lib/auth';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';

	const session = getAuthSession();
	if (!session) goto('/auth', { replaceState: true });

	const destinations = [
		{ id: 1, name: 'AWS S3 Backups', provider: 'aws', bucket: 'rustploy-backups', region: 'us-east-1', status: 'connected' },
		{ id: 2, name: 'DigitalOcean Spaces', provider: 'do', bucket: 'do-backup-space', region: 'nyc3', status: 'connected' }
	];
</script>

<PageLayout>
	<header class="flex items-center gap-2 px-6 py-3 border-b border-border text-sm">
		<Layers class="w-4 h-4 text-muted-foreground" />
		<span class="font-medium">S3 Destinations</span>
	</header>

	<main class="flex-1 p-6 overflow-y-auto animate-fade-up">
		<div class="w-full">
			<Card.Root>
				<Card.Header>
					<div class="flex items-center justify-between">
						<div>
							<Card.Title class="text-base flex items-center gap-2">
								<Layers class="w-4 h-4 text-muted-foreground" />
								S3 Destinations
							</Card.Title>
							<Card.Description>Configure backup destinations for your databases and volumes</Card.Description>
						</div>
						<Button size="sm" class="gap-1.5 text-xs"><Plus class="w-3.5 h-3.5" />Add Destination</Button>
					</div>
				</Card.Header>
				<Card.Content>
					{#if destinations.length === 0}
						<div class="flex flex-col items-center gap-3 min-h-[25vh] justify-center">
							<Layers class="w-8 h-8 text-muted-foreground/40" />
							<p class="text-sm text-muted-foreground">No destinations configured</p>
						</div>
					{:else}
						<div class="flex flex-col gap-2">
							{#each destinations as dest (dest.id)}
								<div class="flex items-center justify-between p-3.5 rounded-lg border">
									<div class="flex items-center gap-3">
										<div class="w-8 h-8 rounded-md bg-primary/10 flex items-center justify-center">
											<Layers class="w-4 h-4 text-primary" />
										</div>
										<div>
											<div class="flex items-center gap-2">
												<span class="text-sm font-medium">{dest.name}</span>
												<Badge variant="default" class="text-[9px] gap-1"><CheckCircle class="w-2.5 h-2.5" />Connected</Badge>
											</div>
											<p class="text-[11px] text-muted-foreground font-mono">{dest.bucket} · {dest.region}</p>
										</div>
									</div>
									<Button variant="ghost" size="sm" class="h-7 w-7 p-0"><Trash2 class="w-3.5 h-3.5 text-destructive" /></Button>
								</div>
							{/each}
						</div>
					{/if}
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</PageLayout>
