// web/rustploy/src/components/ui/BranchSelect.tsx
import { createSignal, createResource, createEffect, For, Show } from 'solid-js';
import { publicListBranches } from '../../client/sdk.gen';
import { RefreshCw } from 'lucide-solid';

type Props = {
  value: string;
  onChange: (v: string) => void;
  // For GIT provider — caller owns the URL input and passes it here reactively
  repoUrl?: string;
  // For hosted providers — we build the URL from owner + repo + provider
  owner?: string;
  repo?: string;
  provider?: string;
};

function buildUrl(props: Props): string {
  if (props.repoUrl) return props.repoUrl;
  if (props.owner && props.repo) {
    const p = (props.provider ?? 'GITHUB').toUpperCase();
    if (p === 'GITHUB')    return `https://github.com/${props.owner}/${props.repo}.git`;
    if (p === 'GITLAB')    return `https://gitlab.com/${props.owner}/${props.repo}.git`;
    if (p === 'GITEA')     return `https://gitea.com/${props.owner}/${props.repo}.git`;
    if (p === 'BITBUCKET') return `https://bitbucket.org/${props.owner}/${props.repo}.git`;
  }
  return '';
}

export default function BranchSelect(props: Props) {
  // fetchKey drives the resource — bump it to force a re-fetch
  const [fetchKey, setFetchKey] = createSignal<{ url: string; tick: number } | null>(null);

  // Debounce auto-fetch when the derived URL changes (e.g. user types in GIT URL field)
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;

  createEffect(() => {
    const url = buildUrl(props).trim();
    if (!url) return;

    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      setFetchKey(prev => ({ url, tick: (prev?.tick ?? 0) + 1 }));
    }, 600);
  });

  const [branches, { refetch }] = createResource(fetchKey, async (key) => {
    if (!key?.url) return [];
    const res = await publicListBranches({ query: { query: { query: key.url } } });
    const raw = (res.data as string[] | undefined) ?? [];
    return raw
      .filter(b => b !== 'HEAD' && !b.startsWith('refs/tags/'))
      .map(b => b.replace('refs/heads/', ''));
  });

  const manualRefresh = (e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    const url = buildUrl(props).trim();
    if (!url) return;
    // bump tick so resource re-runs even if url is the same
    setFetchKey(prev => ({ url, tick: (prev?.tick ?? 0) + 1 }));
  };

  return (
    <div class="flex gap-2 items-center">
      <div class="relative flex-1">
        <select
          class="select select-bordered w-full"
          value={props.value}
          onChange={e => props.onChange(e.currentTarget.value)}
          disabled={branches.loading || !branches()?.length}
        >
          <Show when={branches.loading}>
            <option value="">Loading branches…</option>
          </Show>
          <Show when={!branches.loading && (!branches() || branches()!.length === 0)}>
            <option value="">
              {buildUrl(props) ? 'No branches found' : 'Enter repo URL first'}
            </option>
          </Show>
          <Show when={!branches.loading && (branches()?.length ?? 0) > 0}>
            <option value="">Select branch</option>
            <For each={branches()}>
              {b => <option value={b}>{b}</option>}
            </For>
          </Show>
        </select>

        {/* Loading spinner overlay inside the select row */}
        <Show when={branches.loading}>
          <span class="absolute right-8 top-1/2 -translate-y-1/2 loading loading-spinner loading-xs text-base-content/40 pointer-events-none" />
        </Show>
      </div>

      {/* Manual refresh button — type="button" prevents form submit / page reload */}
      <button
        type="button"
        class="btn btn-ghost btn-sm btn-square"
        onClick={manualRefresh}
        disabled={branches.loading || !buildUrl(props)}
        title="Refresh branches"
      >
        <RefreshCw class={`w-4 h-4 ${branches.loading ? 'animate-spin' : ''}`} />
      </button>
    </div>
  );
}

// web/rustploy/src/lib/components/BranchSelect.svelte
<script lang="ts">
	import { RefreshCw } from '@lucide/svelte';
	import { publicListBranches } from '$lib/client/sdk.gen';

	type Props = {
		value: string;
		onchange: (v: string) => void;
		repoUrl?: string;
		owner?: string;
		repo?: string;
		provider?: string;
	};

	let { value, onchange, repoUrl, owner, repo, provider = 'GITHUB' }: Props = $props();

	let branches = $state<string[]>([]);
	let loading = $state(false);
	let lastFetched = $state('');

	function buildUrl(): string {
		if (repoUrl) return repoUrl.trim();
		if (owner && repo) {
			const p = provider.toUpperCase();
			if (p === 'GITHUB')    return `https://github.com/${owner}/${repo}.git`;
			if (p === 'GITLAB')    return `https://gitlab.com/${owner}/${repo}.git`;
			if (p === 'GITEA')     return `https://gitea.com/${owner}/${repo}.git`;
			if (p === 'BITBUCKET') return `https://bitbucket.org/${owner}/${repo}.git`;
		}
		return '';
	}

	async function fetchBranches(url: string) {
		if (!url || url === lastFetched) return;
		loading = true;
		try {
			const res = await publicListBranches({ query: { query: { query: url } } as any });
			const raw = (res.data as string[] | undefined) ?? [];
			branches = raw
				.filter(b => b !== 'HEAD' && !b.startsWith('refs/tags/'))
				.map(b => b.replace('refs/heads/', ''));
			lastFetched = url;
		} catch {
			branches = [];
		} finally {
			loading = false;
		}
	}

	// Debounce auto-fetch when URL changes
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;

	$effect(() => {
		const url = buildUrl();
		if (!url) return;
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => fetchBranches(url), 600);
	});

	function manualRefresh(e: MouseEvent) {
		e.preventDefault();
		e.stopPropagation();
		lastFetched = ''; // force re-fetch
		fetchBranches(buildUrl());
	}
</script>

<div class="flex gap-2 items-center">
	<div class="relative flex-1">
		<select
			class="h-9 w-full rounded-md border border-input bg-secondary px-3 text-sm focus:outline-none focus:ring-1 focus:ring-ring disabled:opacity-60"
			{value}
			onchange={(e) => onchange((e.target as HTMLSelectElement).value)}
			disabled={loading || branches.length === 0}
		>
			{#if loading}
				<option value="">Loading branches…</option>
			{:else if branches.length === 0}
				<option value="">{buildUrl() ? 'No branches found' : 'Enter repo URL first'}</option>
			{:else}
				<option value="">Select branch</option>
				{#each branches as b}
					<option value={b} selected={value === b}>{b}</option>
				{/each}
			{/if}
		</select>
		{#if loading}
			<div class="absolute right-8 top-1/2 -translate-y-1/2 w-3.5 h-3.5 border-2 border-muted-foreground/30 border-t-muted-foreground rounded-full animate-spin pointer-events-none"></div>
		{/if}
	</div>
	<button
		type="button"
		onclick={manualRefresh}
		disabled={loading || !buildUrl()}
		class="p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent disabled:opacity-40 transition-colors"
		title="Refresh branches"
	>
		<RefreshCw size={14} class={loading ? 'animate-spin' : ''} />
	</button>
</div>
