// web/rustploy/src/components/Sidebar.tsx
import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import {
	Home,
	FolderOpen,
	Zap,
	Clock,
	Globe,
	Package,
	Globe2,
	User,
	Server,
	Users,
	FileText,
	Key,
	Sparkles,
	Tag,
	GitBranch,
	Database,
	Layers,
	Shield,
	Cpu,
	Bell,
	Building2,
	ChevronDown,
	Check,
	ChevronsUpDown,
	Settings
} from 'lucide-react';
import { useSidebarState } from '$lib/sidebar';
import { getAuthSession } from '$lib/auth';

interface SidebarItem {
	label: string;
	icon: React.ComponentType<{ className?: string }>;
	path: string;
}

const navHome: SidebarItem[] = [
	{ label: 'Home', icon: Home, path: '/dashboard' },
	{ label: 'Projects', icon: FolderOpen, path: '/projects' },
	{ label: 'Deployments', icon: Zap, path: '/deployments' },
	{ label: 'Schedules', icon: Clock, path: '/schedules' },
	{ label: 'Traefik File System', icon: Globe, path: '/traefik' },
	{ label: 'Docker', icon: Package, path: '/docker' },
	{ label: 'Swarm', icon: Globe2, path: '/swarm' }
];

const navSettings: SidebarItem[] = [
	{ label: 'Profile', icon: User, path: '/settings/profile' },
	{ label: 'Remote Servers', icon: Server, path: '/remote-servers' },
	{ label: 'Users & Roles', icon: Users, path: '/settings/users' },
	{ label: 'Audit Logs', icon: FileText, path: '/settings/audit-logs' },
	{ label: 'SSH Keys', icon: Key, path: '/ssh-keys' },
	{ label: 'AI Assistant', icon: Sparkles, path: '/settings/ai' },
	{ label: 'Tags', icon: Tag, path: '/settings/tags' },
	{ label: 'Git Integrations', icon: GitBranch, path: '/settings/git-providers' },
	{ label: 'Docker Registry', icon: Database, path: '/settings/registry' },
	{ label: 'S3 Destinations', icon: Layers, path: '/settings/destinations' },
	{ label: 'Certificates', icon: Shield, path: '/settings/certificates' },
	{ label: 'Cluster Config', icon: Cpu, path: '/settings/cluster' },
	{ label: 'Notifications', icon: Bell, path: '/settings/notifications' },
	{ label: 'Server Settings', icon: Settings, path: '/settings/server' },
	{ label: 'Organization Settings', icon: Building2, path: '/settings' }
];

const mockOrganizations = [
	{ id: 'org-1', name: 'My Organization', slug: 'my-org', role: 'Owner' },
	{ id: 'org-2', name: 'Acme Corp', slug: 'acme-corp', role: 'Member' },
	{ id: 'org-3', name: 'Staging Env', slug: 'staging-env', role: 'Admin' }
];

export function Sidebar() {
	const location = useLocation();
	const navigate = useNavigate();
	const { collapsed } = useSidebarState();
	const session = getAuthSession();

	const [activeOrg, setActiveOrg] = useState(mockOrganizations[0]);
	const [orgMenuOpen, setOrgMenuOpen] = useState(false);

	const userEmail = session?.user.email || 'admin@rustploy.dev';

	function isActive(path: string): boolean {
		if (path === '/dashboard') return location.pathname === '/dashboard';
		if (path === '/settings') return location.pathname === '/settings';
		return location.pathname.startsWith(path);
	}

	return (
		<aside
			className={`h-screen shrink-0 border-r border-[#262626] bg-[#0A0A0A] text-[#FAFAFA] flex flex-col justify-between select-none transition-all duration-200 ${
				collapsed ? 'w-[52px]' : 'w-64'
			}`}
		>
			<div className="flex flex-col min-h-0 flex-1">
				{/* Top Header: Organization Switcher */}
				<div className={`p-2.5 border-b border-[#262626] relative ${collapsed ? 'px-2' : 'px-3'}`}>
					{collapsed ? (
						<div
							className="w-7 h-7 mx-auto rounded-lg bg-[#1c1c1c] border border-[#262626] flex items-center justify-center cursor-pointer text-xs font-bold text-[#FAFAFA]"
							title={activeOrg.name}
							onClick={() => setOrgMenuOpen(!orgMenuOpen)}
						>
							{activeOrg.name[0]}
						</div>
					) : (
						<button
							onClick={() => setOrgMenuOpen(!orgMenuOpen)}
							className="w-full flex items-center justify-between p-2 rounded-lg bg-[#141414] hover:bg-[#262626]/80 border border-[#262626] transition-colors cursor-pointer text-left"
						>
							<div className="flex items-center gap-2.5 min-w-0">
								<div className="w-6 h-6 rounded-md bg-[#262626] border border-white/10 flex items-center justify-center shrink-0 font-bold text-xs text-[#FAFAFA]">
									{activeOrg.name[0]}
								</div>
								<div className="min-w-0">
									<p className="text-sm font-bold text-[#FAFAFA] leading-tight truncate">
										{activeOrg.name}
									</p>
									<p className="text-[10px] text-[#a1a1aa] leading-tight font-medium mt-0.5 truncate">
										{activeOrg.role}
									</p>
								</div>
							</div>
							<ChevronsUpDown className="w-4 h-4 text-[#a1a1aa] shrink-0" />
						</button>
					)}

					{/* Org Switcher Dropdown Menu */}
					{orgMenuOpen && (
						<div className="absolute top-full left-2 right-2 mt-1 z-50 bg-[#171717] border border-[#262626] rounded-xl shadow-xl p-1.5 space-y-1">
							<p className="text-[10px] font-semibold uppercase tracking-wider text-[#a1a1aa] px-2 py-1">
								Organizations
							</p>
							{mockOrganizations.map((org) => (
								<button
									key={org.id}
									onClick={() => {
										setActiveOrg(org);
										setOrgMenuOpen(false);
									}}
									className={`w-full flex items-center justify-between px-2.5 py-1.5 rounded-lg text-xs transition-colors cursor-pointer ${
										activeOrg.id === org.id
											? 'bg-[#262626] text-[#FAFAFA] font-semibold'
											: 'text-[#a1a1aa] hover:bg-[#262626]/50 hover:text-[#FAFAFA]'
									}`}
								>
									<div className="flex items-center gap-2 min-w-0">
										<div className="w-5 h-5 rounded bg-[#262626] flex items-center justify-center text-[10px] font-bold">
											{org.name[0]}
										</div>
										<span className="truncate">{org.name}</span>
									</div>
									{activeOrg.id === org.id && <Check className="w-3.5 h-3.5 text-[#FAFAFA]" />}
								</button>
							))}
						</div>
					)}
				</div>

				{/* Scrollable Navigation Menu */}
				<nav className="flex-1 overflow-y-auto px-2 py-3 space-y-4 font-sans text-sm font-bold">
					{/* Main Home Section */}
					<div>
						{!collapsed && (
							<p className="px-3 pb-1.5 text-[11px] font-bold text-[#a1a1aa] uppercase tracking-wider">
								Home
							</p>
						)}
						<div className="space-y-0.5">
							{navHome.map((item) => {
								const active = isActive(item.path);
								const Icon = item.icon;
								return (
									<button
										key={item.path}
										onClick={() => navigate(item.path)}
										title={collapsed ? item.label : undefined}
										className={`w-full flex items-center gap-3 rounded-lg transition-colors cursor-pointer ${
											collapsed ? 'justify-center p-2' : 'px-3 py-2 text-left'
										} ${
											active
												? 'bg-[#262626] text-[#FAFAFA] border border-white/10 font-bold'
												: 'text-[#a1a1aa] hover:bg-[#262626]/50 hover:text-[#FAFAFA]'
										}`}
									>
										<Icon className={`shrink-0 ${collapsed ? 'w-5 h-5' : 'w-4 h-4'}`} />
										{!collapsed && (
											<span className="text-sm font-bold truncate tracking-tight">{item.label}</span>
										)}
									</button>
								);
							})}
						</div>
					</div>

					{/* Settings & Admin Section */}
					<div>
						{!collapsed && (
							<p className="px-3 pb-1.5 text-[11px] font-bold text-[#a1a1aa] uppercase tracking-wider">
								Settings
							</p>
						)}
						<div className="space-y-0.5">
							{navSettings.map((item) => {
								const active = isActive(item.path);
								const Icon = item.icon;
								return (
									<button
										key={item.path}
										onClick={() => navigate(item.path)}
										title={collapsed ? item.label : undefined}
										className={`w-full flex items-center gap-3 rounded-lg transition-colors cursor-pointer ${
											collapsed ? 'justify-center p-2' : 'px-3 py-2 text-left'
										} ${
											active
												? 'bg-[#262626] text-[#FAFAFA] border border-white/10 font-bold'
												: 'text-[#a1a1aa] hover:bg-[#262626]/50 hover:text-[#FAFAFA]'
										}`}
									>
										<Icon className={`shrink-0 ${collapsed ? 'w-5 h-5' : 'w-4 h-4'}`} />
										{!collapsed && (
											<span className="text-sm font-bold truncate tracking-tight">{item.label}</span>
										)}
									</button>
								);
							})}
						</div>
					</div>
				</nav>
			</div>

			{/* User Account Footer */}
			<div className={`border-t border-[#262626] py-3 bg-[#0A0A0A] shrink-0 ${collapsed ? 'px-2 text-center' : 'px-3'}`}>
				{collapsed ? (
					<div
						className="w-7 h-7 mx-auto rounded-full bg-black border border-white/80 text-white text-xs font-bold flex items-center justify-center cursor-pointer"
						title={`Account (${userEmail})`}
					>
						A
					</div>
				) : (
					<div>
						<div className="flex items-center justify-between gap-2.5">
							<div className="flex items-center gap-2.5 min-w-0">
								<div className="w-7 h-7 rounded-full bg-black border border-white/80 text-white text-xs font-bold flex items-center justify-center shrink-0">
									A
								</div>
								<div className="min-w-0">
									<p className="text-sm font-bold text-[#FAFAFA] leading-tight truncate">Account</p>
									<p className="text-xs text-[#a1a1aa] leading-tight truncate mt-0.5">{userEmail}</p>
								</div>
							</div>
						</div>
						<p className="text-[10px] text-[#a1a1aa] font-mono text-center mt-2">Version v0.29.12</p>
					</div>
				)}
			</div>
		</aside>
	);
}

// web/rustploy/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import {
		House,
		FolderOpen,
		Zap,
		Clock,
		Globe,
		Package,
		Globe2,
		User,
		Server,
		Users,
		FileText,
		Key,
		Sparkles,
		Tag,
		GitBranch,
		Database,
		Layers,
		Shield,
		Cpu,
		Bell,
		ChevronsUpDown,
		Loader
	} from '@lucide/svelte';
	import { getAuthSession } from '$lib/auth';
	import { authState } from '$lib/auth.svelte';
	import { sidebarState } from '$lib/sidebar.svelte';
	import { organizationControllerGet } from '$lib/client/sdk.gen';

	const navHome = [
		{ label: 'Home', icon: House, path: '/dashboard' },
		{ label: 'Projects', icon: FolderOpen, path: '/projects' },
		{ label: 'Deployments', icon: Zap, path: '/deployments' },
		{ label: 'Schedules', icon: Clock, path: '/schedules' },
		{ label: 'Traefik File System', icon: Globe, path: '/traefik' },
		{ label: 'Docker', icon: Package, path: '/docker' },
		{ label: 'Swarm', icon: Globe2, path: '/swarm' }
	];

	const navSettings = [
		{ label: 'Profile', icon: User, path: '/settings/profile' },
		{ label: 'Remote Servers', icon: Server, path: '/remote-servers' },
		{ label: 'Users', icon: Users, path: '/settings/users' },
		{ label: 'Audit Logs', icon: FileText, path: '/settings/audit-logs' },
		{ label: 'SSH Keys', icon: Key, path: '/ssh-keys' },
		{ label: 'AI', icon: Sparkles, path: '/settings/ai' },
		{ label: 'Tags', icon: Tag, path: '/settings/tags' },
		{ label: 'Git', icon: GitBranch, path: '/settings/git-providers' },
		{ label: 'Registry', icon: Database, path: '/settings/registry' },
		{ label: 'S3 Destinations', icon: Layers, path: '/settings/destinations' },
		{ label: 'Certificates', icon: Shield, path: '/settings/certificates' },
		{ label: 'Cluster', icon: Cpu, path: '/settings/cluster' }
	];

	const session = $derived(authState.session);
	const userEmail = $derived(session?.user.email || 'dmcbadhya@gmail.com');

	let orgName = $state('…');
	let orgLoading = $state(true);

	$effect(() => {
		const s = session;
		if (!s) return;
		organizationControllerGet({ path: { id: s.user.group_id } }).then((res: { data?: { name?: string } | null }) => {
			orgName = res.data?.name ?? 'My Organization';
			orgLoading = false;
		});
	});

	function isActive(path?: string): boolean {
		if (!path) return false;
		if (path === '/dashboard') return page.url.pathname === '/dashboard';
		if (path === '/settings') return page.url.pathname === '/settings';
		return page.url.pathname.startsWith(path);
	}

	function navItemClass(path?: string): string {
		const base =
			'w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium transition-all duration-150 text-left outline-none';
		if (isActive(path)) return `${base} border border-white/15 bg-[#262626] text-[#FAFAFA] font-semibold shadow-2xs`;
		return `${base} text-[#a1a1aa] hover:bg-[#262626]/40 hover:text-[#FAFAFA]`;
	}

	// Drag-to-resize
	let dragging = $state(false);

	function onDragStart(e: MouseEvent) {
		e.preventDefault();
		dragging = true;
		const onMove = (e: MouseEvent) => {
			sidebarState.width = Math.min(320, Math.max(200, e.clientX));
		};
		const onUp = () => {
			dragging = false;
			window.removeEventListener('mousemove', onMove);
			window.removeEventListener('mouseup', onUp);
		};
		window.addEventListener('mousemove', onMove);
		window.addEventListener('mouseup', onUp);
	}
</script>

<aside
	style="width: {sidebarState.collapsed ? '52px' : `${sidebarState.width}px`}; min-width: {sidebarState.collapsed ? '52px' : `${sidebarState.width}px`}"
	class="relative shrink-0 flex flex-col bg-[#0A0A0A] border-r border-[#262626] h-full text-sidebar-foreground overflow-hidden transition-all duration-200 ease-in-out"
>
	<!-- Org header (Dokploy 1:1) -->
	<div class="flex items-center justify-between px-3 py-3 border-b border-[#262626] h-13 shrink-0">
		{#if sidebarState.collapsed}
			<div class="w-full flex items-center justify-center">
				<span class="w-6 h-6 rounded bg-[#262626] border border-zinc-700/60 flex items-center justify-center text-xs font-bold text-[#FAFAFA] shrink-0">
					M
				</span>
			</div>
		{:else}
			<button class="flex items-center gap-2.5 text-sm font-semibold text-[#FAFAFA] truncate hover:opacity-80 transition-opacity min-w-0">
				<span class="w-6 h-6 rounded bg-[#262626] border border-zinc-700/60 flex items-center justify-center text-xs font-bold text-[#FAFAFA] shrink-0">
					M
				</span>
				<span class="truncate">
					{#if orgLoading}
						<Loader size={14} class="animate-spin opacity-40" />
					{:else}
						{orgName}
					{/if}
				</span>
				<ChevronsUpDown size={14} class="text-[#737373] shrink-0 ml-0.5" />
			</button>
			<button class="text-[#737373] hover:text-[#FAFAFA] p-1 rounded-md transition-colors" title="Notifications">
				<Bell size={16} />
			</button>
		{/if}
	</div>

	<!-- Nav List (14px menu text & 16px icons) -->
	<nav class="flex-1 overflow-y-auto py-2.5 px-2 space-y-1">
		{#if sidebarState.collapsed}
			<!-- Collapsed Icon Rail (18px icons) -->
			<button class="w-9 h-9 mx-auto flex items-center justify-center rounded-lg text-[#737373] hover:text-[#FAFAFA] hover:bg-[#262626]/60 transition-colors mb-1" title="Notifications">
				<Bell size={18} />
			</button>
			{#each navHome as item}
				<button
					class="w-9 h-9 mx-auto flex items-center justify-center rounded-lg text-sm font-medium transition-all outline-none {isActive(item.path) ? 'border border-white/15 bg-[#262626] text-[#FAFAFA]' : 'text-[#a1a1aa] hover:bg-[#262626]/40 hover:text-[#FAFAFA]'}"
					title={item.label}
					onclick={() => item.path && goto(item.path)}
				>
					<item.icon size={18} />
				</button>
			{/each}

			<div class="py-1 px-1">
				<div class="h-[1px] bg-[#262626] w-full"></div>
			</div>

			{#each navSettings as item}
				<button
					class="w-9 h-9 mx-auto flex items-center justify-center rounded-lg text-sm font-medium transition-all outline-none {isActive(item.path) ? 'border border-white/15 bg-[#262626] text-[#FAFAFA]' : 'text-[#a1a1aa] hover:bg-[#262626]/40 hover:text-[#FAFAFA]'}"
					title={item.label}
					onclick={() => item.path && goto(item.path)}
				>
					<item.icon size={18} />
				</button>
			{/each}
		{:else}
			<!-- Expanded Nav (14px text & 16px icons) -->
			<p class="text-xs font-semibold text-[#737373] px-3 pt-2 pb-1">
				Home
			</p>
			{#each navHome as item}
				<button
					class={navItemClass(item.path)}
					onclick={() => item.path && goto(item.path)}
				>
					<item.icon size={16} class="shrink-0" />
					<span class="truncate">{item.label}</span>
				</button>
			{/each}

			<div class="py-2.5 px-2">
				<div class="h-[1px] bg-[#262626] w-full"></div>
			</div>

			<p class="text-xs font-semibold text-[#737373] px-3 pt-1 pb-1">
				Settings
			</p>
			{#each navSettings as item}
				<button
					class={navItemClass(item.path)}
					onclick={() => item.path && goto(item.path)}
				>
					<item.icon size={16} class="shrink-0" />
					<span class="truncate">{item.label}</span>
				</button>
			{/each}
		{/if}
	</nav>

	<!-- Account Footer -->
	<div class="border-t border-[#262626] py-3 bg-[#0A0A0A] shrink-0 {sidebarState.collapsed ? 'px-2 text-center' : 'px-3'}">
		{#if sidebarState.collapsed}
			<div class="w-7 h-7 mx-auto rounded-full bg-black border border-white/80 text-white text-xs font-bold flex items-center justify-center cursor-pointer" title="Account (dmcbadhya@gmail.com)">
				A
			</div>
		{:else}
			<div class="flex items-center justify-between gap-2.5">
				<div class="flex items-center gap-2.5 min-w-0">
					<div class="w-7 h-7 rounded-full bg-black border border-white/80 text-white text-xs font-bold flex items-center justify-center shrink-0">
						A
					</div>
					<div class="min-w-0">
						<p class="text-sm font-semibold text-[#FAFAFA] leading-tight truncate">Account</p>
						<p class="text-xs text-[#737373] leading-tight truncate mt-0.5">{userEmail}</p>
					</div>
				</div>
				<ChevronsUpDown size={14} class="text-[#737373] shrink-0" />
			</div>
			<p class="text-[10px] text-[#737373] font-mono text-center mt-2">Version v0.29.12</p>
		{/if}
	</div>

	<!-- Drag handle (only when expanded) -->
	{#if !sidebarState.collapsed}
		<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
		<div
			onmousedown={onDragStart}
			role="separator"
			tabindex="-1"
			aria-label="Resize sidebar"
			class="absolute top-0 right-0 h-full w-1 cursor-col-resize z-10 transition-colors hover:bg-primary/40 {dragging
				? 'bg-primary/60'
				: ''}"
		></div>
	{/if}
</aside>
