// web/rustploy/src/lib/components/Switch.svelte
<!-- Reusable toggle switch component -->
<script lang="ts">
	type Props = {
		checked: boolean;
		onchange?: (v: boolean) => void;
		id?: string;
		label?: string;
		description?: string;
		disabled?: boolean;
	};
	let { checked, onchange, id, label, description, disabled = false }: Props = $props();
</script>

{#if label}
	<div class="flex items-center justify-between border border-border rounded-lg px-4 py-3 bg-secondary/40">
		<div class="min-w-0 pr-4">
			<p class="text-sm font-medium">{label}</p>
			{#if description}<p class="text-sm text-muted-foreground mt-0.5">{description}</p>{/if}
		</div>
		<button
			type="button"
			{id}
			role="switch"
			aria-checked={checked}
			aria-label={label}
			{disabled}
			onclick={() => !disabled && onchange?.(!checked)}
			class="relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1 disabled:opacity-50 {checked ? 'bg-primary' : 'bg-muted'}"
		>
			<span class="pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow-sm ring-0 transition duration-200 ease-in-out {checked ? 'translate-x-4' : 'translate-x-0'}"></span>
		</button>
	</div>
{:else}
	<button
		type="button"
		{id}
		role="switch"
		aria-checked={checked}
		aria-label="Toggle"
		{disabled}
		onclick={() => !disabled && onchange?.(!checked)}
		class="relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-ring disabled:opacity-50 {checked ? 'bg-primary' : 'bg-muted'}"
	>
		<span class="pointer-events-none inline-block h-4 w-4 rounded-full bg-white shadow-sm ring-0 transition duration-200 ease-in-out {checked ? 'translate-x-4' : 'translate-x-0'}"></span>
	</button>
{/if}

// web/rustploy/src/components/ui/switch.tsx
import * as React from 'react';
import * as SwitchPrimitives from '@radix-ui/react-switch';
import { cn } from '$lib/utils';

const Switch = React.forwardRef<
	React.ElementRef<typeof SwitchPrimitives.Root>,
	React.ComponentPropsWithoutRef<typeof SwitchPrimitives.Root>
>(({ className, ...props }, ref) => (
	<SwitchPrimitives.Root
		className={cn(
			'peer inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-xs transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-[#FAFAFA] data-[state=unchecked]:bg-[#262626]',
			className
		)}
		{...props}
		ref={ref}
	>
		<SwitchPrimitives.Thumb
			className={cn(
				'pointer-events-none block h-4 w-4 rounded-full bg-[#0A0A0A] shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0 data-[state=unchecked]:bg-[#a1a1aa]'
			)}
		/>
	</SwitchPrimitives.Root>
));
Switch.displayName = SwitchPrimitives.Root.displayName;

export { Switch };
