// web/rustploy/src/routes/settings/audit-logs/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { FileText, Search, Filter } from '@lucide/svelte';
	import PageLayout from '$lib/components/PageLayout.svelte';
	import { getAuthSession } from '$lib/auth';
	import * as Card from '$lib/components/ui/card';
	import * as Table from '$lib/components/ui/table';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import { Input } from '$lib/components/ui/input';

	const session = getAuthSession();
	if (!session) goto('/auth', { replaceState: true });

	const logs = [
		{ id: 1, action: 'project.create', user: 'admin@example.com', target: 'Project: my-app', timestamp: '2026-07-12 20:30:00', ip: '192.168.1.1' },
		{ id: 2, action: 'application.deploy', user: 'dev@example.com', target: 'App: frontend', timestamp: '2026-07-12 19:45:00', ip: '192.168.1.2' },
		{ id: 3, action: 'user.login', user: 'admin@example.com', target: '—', timestamp: '2026-07-12 18:00:00', ip: '192.168.1.1' },
		{ id: 4, action: 'database.create', user: 'ops@example.com', target: 'DB: postgres-main', timestamp: '2026-07-12 16:20:00', ip: '192.168.1.3' },
		{ id: 5, action: 'settings.update', user: 'admin@example.com', target: 'Organization settings', timestamp: '2026-07-12 14:10:00', ip: '192.168.1.1' },
		{ id: 6, action: 'compose.deploy', user: 'dev@example.com', target: 'Compose: backend-stack', timestamp: '2026-07-12 12:00:00', ip: '192.168.1.2' }
	];

	let searchQuery = $state('');
	const filtered = $derived(
		logs.filter(l => !searchQuery || l.action.includes(searchQuery) || l.user.includes(searchQuery) || l.target.includes(searchQuery))
	);
</script>

<PageLayout>
	<header class="flex items-center gap-2 px-6 py-3 border-b border-border text-sm">
		<FileText class="w-4 h-4 text-muted-foreground" />
		<span class="font-medium">Audit Logs</span>
	</header>

	<main class="flex-1 p-6 overflow-y-auto animate-fade-up">
		<div class="w-full">
			<Card.Root>
				<Card.Header>
					<div class="flex items-center justify-between">
						<div>
							<Card.Title class="text-base flex items-center gap-2">
								<FileText class="w-4 h-4 text-muted-foreground" />
								Audit Logs
							</Card.Title>
							<Card.Description>Track all actions performed in your organization</Card.Description>
						</div>
						<div class="relative w-64">
							<Search class="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
							<Input bind:value={searchQuery} placeholder="Search logs..." class="pl-9 h-8 text-xs" />
						</div>
					</div>
				</Card.Header>
				<Card.Content class="p-0">
					<Table.Root>
						<Table.Header>
							<Table.Row>
								<Table.Head>Action</Table.Head>
								<Table.Head>User</Table.Head>
								<Table.Head>Target</Table.Head>
								<Table.Head>IP</Table.Head>
								<Table.Head>Timestamp</Table.Head>
							</Table.Row>
						</Table.Header>
						<Table.Body>
							{#each filtered as log (log.id)}
								<Table.Row>
									<Table.Cell><Badge variant="outline" class="text-[10px] font-mono">{log.action}</Badge></Table.Cell>
									<Table.Cell class="text-xs">{log.user}</Table.Cell>
									<Table.Cell class="text-xs text-muted-foreground">{log.target}</Table.Cell>
									<Table.Cell class="text-xs font-mono text-muted-foreground">{log.ip}</Table.Cell>
									<Table.Cell class="text-xs text-muted-foreground">{log.timestamp}</Table.Cell>
								</Table.Row>
							{/each}
						</Table.Body>
					</Table.Root>
				</Card.Content>
			</Card.Root>
		</div>
	</main>
</PageLayout>

// web/rustploy/src/pages/settings/audit-logs/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Search, Shield, Clock } from 'lucide-react';
import { PageLayout } from '$lib/../components/PageLayout';
import { getAuthSession } from '$lib/auth';
import { Card, CardContent } from '$lib/../components/ui/card';
import { Input } from '$lib/../components/ui/input';

export default function AuditLogsPage() {
	const navigate = useNavigate();
	const session = getAuthSession();

	if (!session) {
		setTimeout(() => navigate('/auth', { replace: true }), 0);
	}

	const [logs] = useState([
		{ id: 'log-1', action: 'PROJECT_CREATE', actor: 'admin@rustploy.dev', target: 'web-api-service', ip: '192.168.1.5', time: '10 mins ago' },
		{ id: 'log-2', action: 'SSH_KEY_ADD', actor: 'aman@example.com', target: 'deploy-rsa-key', ip: '10.0.0.12', time: '1 hour ago' },
		{ id: 'log-3', action: 'DEPLOY_TRIGGER', actor: 'system-ci', target: 'rustploy-web #104', ip: '127.0.0.1', time: '3 hours ago' },
		{ id: 'log-4', action: 'TRAEFIK_UPDATE', actor: 'admin@rustploy.dev', target: '/etc/traefik/dynamic/http.yml', ip: '192.168.1.5', time: '1 day ago' }
	]);

	const [query, setQuery] = useState('');

	const filtered = logs.filter((l) =>
		!query || l.action.toLowerCase().includes(query.toLowerCase()) || l.actor.toLowerCase().includes(query.toLowerCase())
	);

	return (
		<PageLayout>
			<header className="flex items-center justify-between px-6 py-3 border-b border-[#262626] text-xs bg-[#0A0A0A] shrink-0">
				<div className="flex items-center gap-2">
					<FileText className="w-3.5 h-3.5 text-[#a1a1aa]" />
					<span className="font-medium text-[#FAFAFA]">Audit Logs</span>
				</div>
			</header>

			<main className="flex-1 m-3.5 overflow-y-auto p-7 animate-fade-up min-h-0">
				<div className="max-w-5xl mx-auto space-y-6">
					<div className="flex items-center justify-between">
						<div>
							<h1 className="text-3xl font-bold tracking-tight text-[#FAFAFA]">Audit Logs</h1>
							<p className="text-sm text-[#a1a1aa] mt-1">Trace all security events, deployments, and configuration mutations</p>
						</div>
					</div>

					<div className="relative max-w-sm">
						<Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#737373]" />
						<Input
							value={query}
							onChange={(e) => setQuery(e.target.value)}
							placeholder="Filter logs by action or user..."
							className="pl-9 text-xs h-9 bg-[#141414] border-[#262626] text-[#FAFAFA]"
						/>
					</div>

					<Card className="bg-[#171717] border border-[#262626] rounded-xl shadow-md overflow-hidden">
						<CardContent className="p-0">
							<table className="w-full text-left text-xs">
								<thead className="bg-[#141414] border-b border-[#262626] text-[#737373] uppercase tracking-wider font-semibold">
									<tr>
										<th className="px-5 py-3">ACTION</th>
										<th className="px-5 py-3">USER / ACTOR</th>
										<th className="px-5 py-3">TARGET</th>
										<th className="px-5 py-3">IP ADDRESS</th>
										<th className="px-5 py-3 text-right">TIME</th>
									</tr>
								</thead>
								<tbody className="divide-y divide-[#262626]">
									{filtered.map((l) => (
										<tr key={l.id} className="hover:bg-[#262626]/30 transition-colors">
											<td className="px-5 py-3.5 font-mono font-semibold text-[#FAFAFA]">{l.action}</td>
											<td className="px-5 py-3.5 text-[#a1a1aa] font-mono">{l.actor}</td>
											<td className="px-5 py-3.5 font-mono text-[#FAFAFA]">{l.target}</td>
											<td className="px-5 py-3.5 font-mono text-[#737373]">{l.ip}</td>
											<td className="px-5 py-3.5 text-right font-mono text-[#737373]">{l.time}</td>
										</tr>
									))}
								</tbody>
							</table>
						</CardContent>
					</Card>
				</div>
			</main>
		</PageLayout>
	);
}
